# Generated by Django 4.2.1 on 2023-05-17 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_customuser_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 11, 12, 29, 932206, tzinfo=datetime.timezone.utc)),
        ),
    ]
