# Generated by Django 4.2.1 on 2023-05-30 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_customuser_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 12, 4, 11, 823253, tzinfo=datetime.timezone.utc)),
        ),
    ]
