# Generated by Django 4.2.1 on 2023-06-12 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_customuser_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 6, 18, 8, 27294, tzinfo=datetime.timezone.utc)),
        ),
    ]
