# Generated by Django 4.2.1 on 2023-06-12 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 17, 59, 31, 603500, tzinfo=datetime.timezone.utc)),
        ),
    ]
