# Generated by Django 4.2.1 on 2023-06-12 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_rename_phone_number_customuser_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 18, 2, 11, 164477, tzinfo=datetime.timezone.utc)),
        ),
    ]
