# Generated by Django 4.2.1 on 2023-06-15 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_customuser_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 7, 33, 29, 247573, tzinfo=datetime.timezone.utc)),
        ),
    ]
