# Generated by Django 4.2.1 on 2023-06-12 06:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_house_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='housephoto',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='houses.house'),
        ),
        migrations.AlterField(
            model_name='housephoto',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='house-photos/'),
        ),
    ]
