# Generated by Django 4.2.1 on 2023-06-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_alter_house_created_at_alter_housephoto_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='agency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='rent_rooms',
            field=models.SmallIntegerField(default=0),
        ),
    ]
