# Generated by Django 4.2.1 on 2023-05-11 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 11, 30, 56, 664847, tzinfo=datetime.timezone.utc)),
        ),
    ]
