# Generated by Django 4.2.1 on 2023-05-11 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_anontoken_alter_customuser_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 12, 15, 52, 343368, tzinfo=datetime.timezone.utc)),
        ),
    ]
