# Generated by Django 4.2.1 on 2023-05-11 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 12, 16, 7, 252093, tzinfo=datetime.timezone.utc)),
        ),
    ]
