# Generated by Django 4.2.1 on 2023-05-17 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customuser_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 10, 28, 23, 584078, tzinfo=datetime.timezone.utc)),
        ),
    ]
